<?php
use Perspective\Voting\Block\VotingList;
/* @var VotingList $block */
$votingIds = $block->getVotingIds();
?>

<div class="votings-grid">
    <?php if (!empty($votingIds)): ?>
        <?php foreach ($votingIds as $id): ?>
            <div class="voting-item-card">
                <?= $block->getChildBlock('voting.widget.renderer')
                    ->setData('voting_id', $id)
                    ->toHtml();
                ?>
            </div> <br>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="message info">
            <span><?= $block->escapeHtml(__('No voting available.')) ?></span>
        </div>
    <?php endif; ?>
</div>
