
<?php //modified vendor/hyva-themes/magento2-default-theme/Magento_Catalog/templates/product/slider/product-slider.phtml
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductList;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\Store;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Perspective\PopularProductsFromOrders\ViewModel\PopularProduct;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var PopularProduct $popularProductListViewModel */
$popularProductListViewModel = $viewModels->require(PopularProduct::class);
$items = $popularProductListViewModel->getItems();
if (!$items) {
    return '';
}

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var ProductList $productListViewModel */
$productListViewModel = $viewModels->require(ProductList::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var Store $storeViewModel */
$storeViewModel = $viewModels->require(Store::class);

$sliderName = $block->getSliderName() ?: str_replace(['.', '/', '\\'], '_', $block->getNameInLayout());
$title = $block->getTitle() ?: '';
$headingTag = $block->getHeadingTag() ?: 'h3';
$cssClasses = $block->getCssClasses() ?: 'product-slider my-8';
$headingCssClasses = $block->getHeadingCssClasses() ?: 'text-2xl font-medium';
$columnCount = $block->getColumnCount() ?? 4;
$sliderClasses = implode(' ', array_filter([
    'snap-track',
    $columnCount > 1 ? 'md:[--snap-cols:2]' : '',
    $columnCount > 2 ? 'lg:[--snap-cols:3]' : '',
    $columnCount > 3 ? 'xl:[--snap-cols:4]' : '',
    $columnCount > 4 ? '2xl:[--snap-cols:5]' : '',
    $block->getSliderCssClasses()
]));

$showHeading = $block->getShowHeading() ?? true;
$showPager = $block->getShowPager() ?? true;
$hideDetails = $block->getHideDetails() ?? false;
$hideRatingSummary = $block->getHideRatingSummary() ?? false;

// Filter Options
$pageSize = null;
$sortDirection = $block->getSortDirection() ?: 'ASC';

$type = $block->getType();
// In case $type is not set on the block, it will default the block class name, which is not what we need in this template.
$type = is_string($type) && strpos($type, '\\') === false  ? $type : 'generic';

if ($hideRatingSummary) {
    $productListViewModel->excludeReviewSummary();
}

if ($isAnchorCategory = $block->getIncludeChildCategoryProducts()) {
    // Only has an effect if a single category ID filter is set, and that category is an anchor category
    $productListViewModel->includeChildCategoryProducts();
}

$productListViewModel->setPageSize($pageSize);
$productListViewModel->addFilter('website_id', $storeViewModel->getWebsiteId());

$itemRenderer = $block->getLayout()->getBlock('product_list_item')
    ?: $block->getChildBlock('slider.item.template')
        ?: $block->getLayout()->createBlock(Template::class);

$itemRenderer->setData('hide_details', $hideDetails);
?>
<section
    id="<?= $escaper->escapeHtmlAttr($sliderName) ?>"
    class="snap-slider <?= $escaper->escapeHtmlAttr($cssClasses) ?>"
    aria-label="<?= $escaper->escapeHtmlAttr($title); ?>"
    data-slider-type="<?= $escaper->escapeHtmlAttr($type) ?>"
    x-data
    x-snap-slider.group-pager
    x-defer="intersect"
>
    <a
        href="#<?= $escaper->escapeHtmlAttr($sliderName) ?>-slider-end"
        class="sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
    ><?= $escaper->escapeHtml(__('Press to skip carousel')) ?></a>

    <div class="flex gap-2 justify-between items-center">
        <?php if ($showHeading): ?>
            <?= $escaper->escapeHtml(str_replace(
                ['%1', '%2', '%3'],
                [$headingTag, $title, $headingCssClasses],
                '<%1 class="%3">%2</%1>'
            ), ['h1', 'h2', 'h3', 'h4', 'h5', 'h6']) ?>
        <?php endif; ?>
        <div class="flex gap-2">
            <button
                class="btn btn-secondary p-2 invisible"
                aria-label="Previous Slide"
                data-prev
                disabled
            ><?= $lucideIcons->arrowLeftHtml('rtl:-rotate-180', 18, 18, ['aria-hidden' => 'true']); ?></button>
            <button
                class="btn btn-secondary p-2 invisible"
                aria-label="Next Slide"
                data-next
                disabled
            ><?= $lucideIcons->arrowRightHtml('rtl:-rotate-180', 18, 18, ['aria-hidden' => 'true']); ?></button>
        </div>
    </div>

    <div class="<?= $escaper->escapeHtmlAttr($sliderClasses) ?>" data-track tabindex="0" aria-live="polite">
        <?php
            $rank = 1;
            foreach ($items as $product):?>
            <div
                id="<?= $escaper->escapeHtmlAttr($sliderName . '-' . $product->getId()) ?>"
                class="flex flex-col"
                role="tabpanel"
            >

                <?= $escaper->escapeHtml(__('Top %1', $rank)) ?>

                <?= /** @noEscape */ $productListItemViewModel->getItemHtmlWithRenderer(
                    $itemRenderer,
                    $product,
                    $block,
                    'grid',
                    ProductReviewRenderer::SHORT_VIEW,
                    'category_page_grid',
                    false
                ) ?>
            </div>
        <?php
            $rank++;
            endforeach; ?>
    </div>

    <?php if ($showPager): ?>
        <div class="snap-pager" data-pager>
            <?php foreach ($items as $product): ?>
                <a
                    href="#<?= $escaper->escapeHtmlAttr($sliderName . '-' . $product->getId()) ?>"
                    class="snap-marker"
                    role="tab"
                    x-cloak
                >
                    <span class="sr-only">
                        <?= $escaper->escapeHtmlAttr(__('View more about %1', $product->getName())) ?>
                    </span>
                </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <span id="<?= $escaper->escapeHtmlAttr($sliderName) ?>-slider-end" tabindex="-1"></span>
</section>
