<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Perspective\B2BCheckout\Magewire\Checkout\CompanyInfo;

/** @var Template $block */
/** @var CompanyInfo $magewire */
/** @var Escaper $escaper */
?>

<div id="company-container" class="border-t border-gray-400 pt-4">
    <div class="field field-reserved">
        <textarea
            id="company_name"
            type="text"
            name="company_name"
            wire:model.live.debounce.750ms="companyName"
            wire:key="company-name-key"
            placeholder="<?= $escaper->escapeHtmlAttr(__('Company Name')) ?>"
            class="block w-full shadow-sm border-gray-300 rounded-md resize-y">
        </textarea>
    </div>

    <div class="field field-reserved">
        <textarea
            id="vat_number"
            type="text"
            name="vat_number"
            wire:model.live.debounce.750ms="vatNumber"
            wire:key="vat-number-key"
            placeholder="<?= $escaper->escapeHtmlAttr(__('VAT Number')) ?>"
            class="block w-full shadow-sm border-gray-300 rounded-md resize-y">
        </textarea>
    </div>
</div>
