<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Adminhtml\Order\View;
use Perspective\CheckoutExtensionAttributes\ViewModel\Checkout\CustomerReference;

/** @var View $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var CustomerReference $viewModel */

$viewModel = $viewModels->require(CustomerReference::class);
?>

<?php if ($customerReference = $viewModel->getCustomerReference($block->getOrder()->getQuoteId())): ?>
    <div class="note-list-comment">
    <span class="note-list-customer">
        <?= $escaper->escapeHtml(__('Customer Reference: ')) ?>
    </span>
        <?= $escaper->escapeHtml($customerReference, ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
    </div>
<?php endif; ?>
