<?php
/** @var Template $block */
/** @var OrderDeliveryComment $magewire */
/** @var Escaper $escaper */
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Perspective\CheckoutDeliveryComment\Magewire\Checkout\OrderDeliveryComment;
?>

<div class="border-t border-gray-400 pt-4">
    <h2 class="text-2xl font-bold mb-6 text-blue-900">
        <?= $escaper->escapeHtmlAttr(__('Additional Information')) ?>
    </h2>
    <div class="space-x-4 text-sm">
        <span class="hidden text-purple-700"
              wire:loading
              wire:target="orderDeliveryComment"
              wire:loading.class.remove="hidden">
            ...<?= $escaper->escapeHtml(__('saving!')) ?>
        </span>

        <?php if ($magewire->saved): ?>
            <span wire:target="orderDeliveryComment" class="flex text-primaryGreen" wire:loading.class="hidden">
                <?= $escaper->escapeHtml(__('Saved successfully!')) ?>
            </span>
        <?php endif ?>
    </div>

    <div class="field field-reserved">
        <textarea
            id="order_delivery_comment"
            type="text"
            name="order_delivery_comment"
            wire:model.live.debounce.750ms="orderDeliveryComment"
            wire:key="order-delivery-comment-key"
            placeholder="<?= $escaper->escapeHtmlAttr(__('Order Delivery Comment')) ?>"
            class="block w-full shadow-sm border-gray-300 rounded-md resize-y">
        </textarea>
    </div>

    <?php if ($magewire->isBlockCartButton): ?>
        <span class="text-red-600" id="order-delivery-comment-error">
             <?= $escaper->escapeHtml(__('Delivery Comment must not contain the word "test".')) ?>
        </span>
    <?php endif ?>
</div>
