<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Perspective\CheckoutDeliveryComment\ViewModel\Checkout\OrderDelivery;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var OrderDelivery $viewModel */

$viewModel = $viewModels->require(OrderDelivery::class);
$orderComment = $viewModel->getOrderComment();
?>
<div>
    <?php if ($orderComment): ?>
        <div>
            <div class="section-title border-b border-slate-300 pb-1 mb-6">
                <h2 class="text-slate-800 text-xl font-medium">
                    <?= $escaper->escapeHtml((__('Comment to order'))) ?>
                </h2>
            </div>

            <p class="break-all">
                <?= $escaper->escapeHtml($orderComment)?>
            </p>
        </div>
    <?php endif ?>
</div>
